ci: improve workflow
- Support `EXTENSION_NAME_SUFFIX`, `FIREFOX_EXTENSION_ID`, and `FIREFOX_EXTENSION_CHANNEL` environment variables.
- Skip changelog checking and Git tag generating for non-production environment.
- Skip specific job if envvar not set.
- Remove `publish-mv3.yml`.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -29,6 +29,10 @@ jobs:
       artifact_zip: ${{ steps.config.outputs.artifact_zip }}
       artifact_xpi: ${{ steps.config.outputs.artifact_xpi }}
 
+      publish_firefox: ${{ steps.config.outputs.publish_firefox }}
+      publish_chrome: ${{ steps.config.outputs.publish_chrome }}
+      publish_edge: ${{ steps.config.outputs.publish_edge }}
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -47,10 +51,12 @@ jobs:
             fi
           done
 
-          EXPECTED_LINE="## [$VERSION] - $(TZ="$TIMEZONE" date +%Y-%m-%d)"
-          if ! grep -Fxq "$EXPECTED_LINE" CHANGELOG.md; then
-            echo "❌ Missing expected changelog line: $EXPECTED_LINE"
-            exit 1
+          if [ '${{ github.event.inputs.environment }}' = 'production' ]; then
+            EXPECTED_LINE="## [$VERSION] - $(TZ="$TIMEZONE" date +%Y-%m-%d)"
+            if ! grep -Fxq "$EXPECTED_LINE" CHANGELOG.md; then
+              echo "❌ Missing expected changelog line: $EXPECTED_LINE"
+              exit 1
+            fi
           fi
 
           echo "version=$VERSION" >> $GITHUB_OUTPUT
@@ -60,6 +66,28 @@ jobs:
           echo "artifact_dir=dist" >> $GITHUB_OUTPUT
           echo "artifact_zip=webscrapbook-zip" >> $GITHUB_OUTPUT
           echo "artifact_xpi=webscrapbook-xpi" >> $GITHUB_OUTPUT
+
+          echo "publish_firefox=$([ -z "${{ vars.FIREFOX_EXTENSION_CHANNEL }}" ] && echo '' || echo '1')" >> $GITHUB_OUTPUT
+          echo "publish_chrome=$([ -z "${{ vars.CHROME_EXTENSION_ID }}" ] && echo '' || echo '1')" >> $GITHUB_OUTPUT
+          echo "publish_edge=$([ -z "${{ vars.EDGE_PRODUCT_ID }}" ] && echo '' || echo '1')" >> $GITHUB_OUTPUT
+
+      - name: Set extension name suffix
+        if: vars.EXTENSION_NAME_SUFFIX != ''
+        run: |
+          for file in src/_locales/*/messages.json; do
+            echo "Updating '$file'..."
+            jq '.ExtensionName.message += "${{ vars.EXTENSION_NAME_SUFFIX }}"' "$file" > .tmp.json
+            mv .tmp.json "$file"
+          done
+
+      - name: Set Firefox extension ID
+        if: vars.FIREFOX_EXTENSION_ID != ''
+        run: |
+          for file in src/manifest.firefox*.json; do
+            echo "Updating '$file'..."
+            jq '.browser_specific_settings.gecko.id = "${{ vars.FIREFOX_EXTENSION_ID }}"' "$file" > .tmp.json
+            mv .tmp.json "$file"
+          done
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -76,6 +104,7 @@ jobs:
         run: npm run pack
 
       - name: Create Git tag
+        if: github.event.inputs.environment == 'production'
         run: |
           git tag --force ${{ steps.config.outputs.tag_name }}
           git push origin ${{ steps.config.outputs.tag_name }}
@@ -94,6 +123,7 @@ jobs:
 
   upload_cws:
     name: Upload to Chrome Web Store
+    if: needs.main.outputs.publish_chrome != ''
     runs-on: ubuntu-latest
     needs: main
     environment: ${{ github.event.inputs.environment }}
@@ -117,6 +147,7 @@ jobs:
 
   upload_edge:
     name: Upload to Microsoft Edge Add-ons
+    if: needs.main.outputs.publish_edge != ''
     runs-on: ubuntu-latest
     needs: main
     environment: ${{ github.event.inputs.environment }}
@@ -137,6 +168,7 @@ jobs:
 
   upload_firefox:
     name: Upload to Firefox Add-ons
+    if: needs.main.outputs.publish_firefox != ''
     runs-on: ubuntu-latest
     needs: main
     environment: ${{ github.event.inputs.environment }}
@@ -151,7 +183,10 @@ jobs:
         uses: kewisch/action-web-ext@v1
         with:
           cmd: sign
-          channel: listed
+
+          # 'listed' or 'unlisted'
+          channel: ${{ vars.FIREFOX_EXTENSION_CHANNEL }}
+
           source: ${{ needs.main.outputs.ext_path_xpi }}
           artifacts: dist
           apiKey: ${{ secrets.FIREFOX_API_KEY }}
